spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transporte?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: senha123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/transporte_nosql

server:
  port: 8080
